"""empty message

Revision ID: fd4c000629f8
Revises: 
Create Date: 2019-06-10 15:13:00.789726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4c000629f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('c_address', sa.String(length=255), nullable=False),
    sa.Column('c_mobileno', sa.Integer(), nullable=False),
    sa.Column('c_email', sa.String(length=255), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_table('items',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_quantity', sa.String(length=255), nullable=False),
    sa.Column('item_price', sa.String(length=255), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.CheckConstraint('item_quantity > 0'),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=255), server_default='', nullable=False),
    sa.Column('password', sa.String(length=255), server_default='', nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='rolesavailable'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('sales_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=True),
    sa.Column('i_id', sa.Integer(), nullable=True),
    sa.Column('sale_quantity', sa.String(length=255), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['customers.c_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['i_id'], ['items.i_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('i_id', sa.Integer(), nullable=True),
    sa.Column('c_id', sa.Integer(), nullable=True),
    sa.Column('o_id', sa.Integer(), nullable=True),
    sa.Column('bill_amount', sa.String(length=255), nullable=False),
    sa.Column('bill_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['items.i_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['i_id'], ['customers.c_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['o_id'], ['sales_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    op.drop_table('sales_items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('items')
    op.drop_table('customers')
    # ### end Alembic commands ###
